name: Monk CI Shield
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security-scan:
    uses: MonkCi-Inc/security-workflows/.github/workflows/monkci-security-scan.yml@main
    with:
      enable_gitleaks: true
      enable_semgrep: true
      enable_trivy: true
      enable_checkov: true
    permissions:
      contents: read
      pull-requests: write
      security-events: write
      checks: write
